### PR TITLE
add eslint with prettier configuration

### PR DESCRIPTION
**Pull request by dagda1**
I've added eslint with prettier so we can stop worrying about semi-colons and the like.

I've added an npm `lint` script and a `lint:fix` script.

There are currently a couple of warnings rightly highlighted by the `react-hooks/exhaustive-deps`

But these will go away once I merge my `pc/suggested-improvements` gets merged into mater and master gets merged in here.

Feel free to tweak the prettier configuration [here](https://github.com/alex-cory/use-http/pull/42/files#diff-df39304d828831c44a2b9f38cd45289cR51) and then run `npm run lint:fix`.

If you use vscode and you get this set up it will run `eslint --fix` on every save and is such a great expreience.

I blogged about it [here](https://thesoftwaresimpleton.com/blog/2019/05/07/eslint)

A lot of white space changes or double quotes becoming quotes.  Just concntrate on the `.eslint.json` file and run `npm run lint:fix` to change the entire codebase.

### CODE REVIEW

**Comment by alex-cory** [comment]
dude, I added this with my other branch lol

**Comment by alex-cory** [comment]
I'm just gonna merge what I have so we don't have any more problems lol but please review my other branch cuz it has all these things done. We can improve them, but I feel bad that we're doing double the work :(

**Comment by alex-cory** [comment]
maybe move the config to `package.json` and we can merge this before merging mine?

**Comment by alex-cory** [comment]
Btw, thank you for all your help! :) Sorry we're accidentally stepping on eachother's toes

**Comment by dagda1** [comment]
i think .eslint.json is the right place.  the package.json has enough going on.

take a look at nearly anh other oss project and it wrong have eslint  configurations in the package.json

**Comment by dagda1** [comment]
this literally took me about 20 minutes copying from another project so don’t worry.

i’ll shout on spectrum before amy more PRs

**Comment by dagda1** [comment]
no need to say thank you and it is my fault for not checking first

**Comment by alex-cory** [comment]
I want this so whatever we gotta do to get this merged 😊

**Comment by dagda1** [comment]
NOt sure what you want to do here, there are 2 completely different eslint setups in master and this branch.

**Comment by alex-cory** [comment]
Let's use `.eslint.json` as you suggested. Here are my suggestions for the config
```json
{
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "@typescript-eslint",
        "react",
        "react-hooks",
        "jest",
        "jest-formatting"
    ],
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:react/recommended",
        "plugin:jest/recommended",
        "prettier/@typescript-eslint",
        "plugin:prettier/recommended"
    ],
    "rules": {
        "@typescript-eslint/member-delimiter-style": [
            "error",
            {
                "multiline": {
                    "delimiter": "none",
                    "requireLast": false
                },
                "singleline": {
                    "delimiter": "comma",
                    "requireLast": false
                }
            }
        ],
        "@typescript-eslint/explicit-member-accessibility": [
            "off"
        ],
        "@typescript-eslint/explicit-function-return-type": [
            "off"
        ],
        "@typescript-eslint/no-explicit-any": [
            "off"
        ],
        // might not need the next 2 rules since prettier might handle 2 space tabs
        "indent": "off",
        "@typescript-eslint/indent": [
            "error",
            2
        ],
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "warn",
        "jest/consistent-test-it": [
            "error",
            {
                "fn": "it"
            }
        ],
        "jest-formatting/padding-before-test-blocks": 2,
        "jest-formatting/padding-before-describe-blocks": 2,
        "react/prop-types": 0,
        "prefer-const": "warn",
        "no-var": "warn",
        "prettier/prettier": [
            "error",
            {
                "printWidth": 80,
                "singleQuote": true,
                "semi": false,
                "tabWidth": 2,
                "trailingComma": "all"
            }
        ]
    },
    "settings": {
        "react": {
            "version": "detect"
        }
    }
} 
```
Do you think we should leave the `eslintIgnore` field in the`package.json`?

**Comment by dagda1** [comment]
@alex-cory I think package.json is for packages.  There is enough going on in there, I've added an `.eslintignore` file.

**Comment by alex-cory** [comment]
Once the checks pass, merging

**Pull request merged**
