### PR TITLE
Port to TypeScript

### PR DESCRIPTION
**Pull request by g-plane**
The TypeScript declarations will be generated automatically.

### CODE REVIEW

**Comment by alex-cory** [comment]
I'm taking a look at this PR tonight. I'll fix these merge conflicts :)

**Comment by alex-cory** [comment]
Still need to fix conflicts and run some more tests. Will merge tomorrow

**Comment by g-plane** [comment]
However, I can't fix resolve conflicts here.

**Comment by g-plane** [comment]
I have resolved conflicts and now you can merge it.

**Comment by alex-cory** [comment]
Did you test this server side?

**Comment by g-plane** [comment]
Do you mean SSR?

**Comment by alex-cory** [comment]
to make sure it will work with SSR yes

**Comment by g-plane** [comment]
I didn't, but I have run the unit tests.

**Comment by g-plane** [comment]
So how should I test it?

**Comment by alex-cory** [comment]
you just need to run `node dist/index.js` and if there's any errors, then something is up

**Comment by g-plane** [comment]
There's no any output in terminal.

**Pull request merged**
