### PR TITLE
updated browser check to allow FormData to be sent raw also in react-native

### PR DESCRIPTION
**Pull request by TheDuc**
in doFetchArgs, routeOrBody and bodyAs2ndParam is stringified.
This poses a problem when sending FormData, as it is not seen as FormData anymore.
A normal fetch() request with the same data is working.

I traced this stringify change back to this daba3fdecfd32a757f4b1f56dc7824415c836a27 commit, I am not sure why JSON.stringify is neccessary here.

This merge request solves the problem simply by removing the JSON.stringify statements

### CODE REVIEW

**Comment by TheDuc** [comment]
I'm sorry, removing JSON.stringify introduced other bugs when making a POST call.
the isBrowser check evaluates to false in react-native, so FormData is never sent raw.
I changed the isBrowser check to !isServer, and added the checks for react-native from use-ssr

**Comment by alex-cory** [comment]
I will take a look at this asap

**Comment by alex-cory** [comment]
The reason for the `JSON.stringify` is for relative routes.
```js
const [request] = useFetch()
request.post('/todos', {
  name: 'todo 1'
})
```

**Comment by TheDuc** [comment]
yes, removing it did not fix the issue.
The problem was the browsercheck, that failed when using react-native

**Comment by alex-cory** [comment]
We need tests added for this. Would greatly appreciate if you could add one.

**Comment by alex-cory** [comment]
You can see this change in `v0.2.9`

**Pull request merged**
