### PR TITLE
Bug/use fetch cache dependencies

### PR DESCRIPTION
**Pull request by maxquinn**

### CODE REVIEW

**Comment by maxquinn** [comment]
Looks like this could be a go - https://jestjs.io/docs/en/timer-mocks.html

**Comment by alex-cory** [comment]
Is this good to go? I wanna get this merged asap so I can get some of these other bugs fixed

**Comment by maxquinn** [comment]
Could you double check the tests? I think i've resolved the timeout issues.

**Comment by alex-cory** [comment]
Beautiful. Checking now

**Comment by alex-cory** [comment]
[This is what I did to fix your last commit.](https://github.com/alex-cory/use-http/commit/2edcc3b29215cc1fbacff6b801f47dc8d9a05798#diff-34a7b559b446746b2b707add8f74eefbL263-L344) Ignore the commented out stuff.

**Comment by maxquinn** [comment]
That all looks good! I take it you were getting TS errors re. the commented out code. I ended up disabling it while I was working on it for that reason haha.

**Comment by alex-cory** [comment]
I was lol

**Pull request merged**
